_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 13
                - 16
                - 55
                - 61
            "4": 3.8.20
            "5": 0.20.1
            "6": 4.46.3
            "12": 0.20.1
            "13": linux-x86_64
code_length:
    value: 512
data_flow_length:
    value: 128
epochs:
    value: 1
eval_batch_size:
    value: 6
learning_rate:
    value: 2e-05
max_grad_norm:
    value: 1
model_name:
    value: microsoft/graphcodebert-base
seed:
    value: 123456
train_batch_size:
    value: 6
warmup_steps:
    value: 0
weight_decay:
    value: 0
